/// @description  Reactivate start hud
instance_activate_object(htme_obj_menu_button);
instance_activate_object(htme_obj_player1choose);
instance_activate_object(htme_obj_player2choose);
instance_activate_object(htme_obj_player1_lArrow);
instance_activate_object(htme_obj_player1_rArrow);
instance_activate_object(htme_obj_player2_lArrow);
instance_activate_object(htme_obj_player2_rArrow);

